# Generated by Django 6.0.5 on 2026-06-05 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('idProspect', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('nomComplet', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('codePostal', models.CharField(max_length=20)),
                ('pays', models.CharField(max_length=100)),
                ('sexe', models.CharField(max_length=10)),
                ('dateNaissance', models.DateField(blank=True, null=True)),
                ('niveauEtude', models.CharField(max_length=100)),
                ('domaineEtude', models.CharField(max_length=100)),
                ('typeProspect', models.CharField(max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'prospect',
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('idRendezVous', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('dateRendezVous', models.DateTimeField()),
                ('sujet', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('idProspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospect_api.prospect')),
            ],
            options={
                'db_table': 'rendezvous',
            },
        ),
        migrations.CreateModel(
            name='SuiviProspect',
            fields=[
                ('idSuivi', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('dateSuivi', models.DateTimeField()),
                ('commentaire', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('idProspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospect_api.prospect')),
            ],
            options={
                'db_table': 'suiviprospect',
            },
        ),
    ]
