# Generated by Django 6.0.5 on 2026-06-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect_api', '0002_prospect_nomparent_prospect_numeroparent'),
    ]

    operations = [
        migrations.AddField(
            model_name='suiviprospect',
            name='libeleSuivi',
            field=models.CharField(default='Nouveau suivi', max_length=255),
        ),
    ]
