# Generated by Django 6.0.5 on 2026-06-10 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect_api', '0003_suiviprospect_libelesuivi'),
        ('specialite_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='specialiteInteret',
            field=models.ManyToManyField(through='specialite_api.interetSpecialite', to='specialite_api.specialite'),
        ),
        migrations.CreateModel(
            name='Relance',
            fields=[
                ('idRelance', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('dateRelance', models.DateTimeField()),
                ('sujet', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('idProspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospect_api.prospect')),
            ],
            options={
                'db_table': 'relance',
            },
        ),
    ]
