# Generated by Django 6.0.5 on 2026-07-03 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prospect_api', '0005_alter_prospect_adresse_alter_prospect_codepostal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospect',
            name='dateNaissance',
        ),
    ]
