# Generated by Django 6.0.5 on 2026-07-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect_api', '0006_remove_prospect_datenaissance'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='dateNaissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='typeProspect',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
