# Generated by Django 6.0.6 on 2026-07-15 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagne_api', '0004_remove_fichesortie_idprospect'),
        ('prospect_api', '0007_prospect_datenaissance_alter_prospect_typeprospect'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='idFiche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campagne_api.fichesortie'),
        ),
    ]
