# Generated by Django 6.0.5 on 2026-06-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='dateEmbauche',
            field=models.DateField(blank=True, null=True),
        ),
    ]
