# Generated by Django 6.0.5 on 2026-06-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_utilisateur_dateembauche'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='photoProfil',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
