# Generated by Django 6.0.5 on 2026-06-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagne_api', '0002_alter_participation_dateassignation_and_more'),
        ('user_api', '0003_utilisateur_photoprofil'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='sortie',
            field=models.ManyToManyField(blank=True, related_name='participations', through='campagne_api.Participation', to='campagne_api.sortie'),
        ),
    ]
