# Generated by Django 6.0.5 on 2026-06-06 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prospect_api', '0002_prospect_nomparent_prospect_numeroparent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('idSpecialite', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('libeleSpecialite', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'specialite',
            },
        ),
        migrations.CreateModel(
            name='interetSpecialite',
            fields=[
                ('idInteret', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('niveauInteret', models.CharField(max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('idProspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospect_api.prospect')),
                ('idSpecialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialite_api.specialite')),
            ],
            options={
                'db_table': 'interetspecialite',
            },
        ),
    ]
