# Generated by Django 6.0.5 on 2026-07-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialite_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialite',
            name='acronyme',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
