# Generated by Django 6.0.5 on 2026-06-05 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prospect_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampagneProspection',
            fields=[
                ('idCampagne', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('libele', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('dateDebut', models.DateTimeField()),
                ('dateFin', models.DateTimeField()),
                ('objectif', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'campagneprospect',
            },
        ),
        migrations.CreateModel(
            name='source',
            fields=[
                ('idSource', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('libele', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'source',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('idZone', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('libele', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('quartier', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('lieuDepart', models.CharField(max_length=100)),
                ('lieuArrivee', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'zone',
            },
        ),
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('idSortie', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('dateSortie', models.DateTimeField()),
                ('statut', models.CharField(max_length=50)),
                ('typeSortie', models.CharField(max_length=50)),
                ('objectif', models.CharField(max_length=255)),
                ('commentaire', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('idCampagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campagne_api.campagneprospection')),
                ('idZone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campagne_api.zone')),
            ],
            options={
                'db_table': 'sortie',
            },
        ),
        migrations.CreateModel(
            name='participation',
            fields=[
                ('idParticipation', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('dateAssignation', models.CharField(max_length=50)),
                ('heureArrivee', models.CharField(max_length=50)),
                ('heureDepart', models.TimeField()),
                ('statut', models.CharField(max_length=50)),
                ('observation', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('idUtilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idSortie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campagne_api.sortie')),
            ],
            options={
                'db_table': 'participation',
            },
        ),
        migrations.CreateModel(
            name='ficheSortie',
            fields=[
                ('idFiche', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('dateCollecte', models.DateTimeField()),
                ('commentaire', models.TextField()),
                ('scoreInteret', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('idProspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospect_api.prospect')),
                ('idParticipation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campagne_api.participation')),
                ('idSource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campagne_api.source')),
            ],
            options={
                'db_table': 'fichesortie',
            },
        ),
    ]
