# Generated by Django 6.0.5 on 2026-06-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagne_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='dateAssignation',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='participation',
            name='heureArrivee',
            field=models.TimeField(),
        ),
    ]
