# Generated by Django 6.0.5 on 2026-06-16 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagne_api', '0002_alter_participation_dateassignation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('idEtablissement', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'etablissement',
            },
        ),
        migrations.AddField(
            model_name='sortie',
            name='idEtablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campagne_api.etablissement'),
        ),
    ]
