# Generated by Django 6.0.6 on 2026-07-15 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campagne_api', '0003_etablissement_sortie_idetablissement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichesortie',
            name='idProspect',
        ),
    ]
